const cards10 = [
  { image: "/images/Firefly חיה חמודה 4429.jpg", value: "value1", isMatched: false },
  { image: "/images/Firefly חיה חמודה 4429.jpg", value: "value1", isMatched: false },
  { image: "/images/Firefly חיה חמודה 12611.jpg", value: "value2", isMatched: false },
  { image: "/images/Firefly חיה חמודה 12611.jpg", value: "value2", isMatched: false },
  { image: "/images/Firefly חיה חמודה 25906.jpg", value: "value3", isMatched: false },
  { image: "/images/Firefly חיה חמודה 25906.jpg", value: "value3", isMatched: false },
  { image: "/images/Firefly חיה חמודה 35860.jpg", value: "value4", isMatched: false },
  { image: "/images/Firefly חיה חמודה 35860.jpg", value: "value4", isMatched: false },
  { image: "/images/Firefly חיה חמודה 33027.jpg", value: "value5", isMatched: false },
  { image: "/images/Firefly חיה חמודה 33027.jpg", value: "value5", isMatched: false }
];
const cards20 = [
  { image: "/images/image1.png", value: "value1" },
  { image: "/images/image1.png", value: "value1" },
  { image: "/images/image2.png", value: "value2" },
  { image: "/images/image2.png", value: "value2" },
  { image: "/images/image3.png", value: "value3" },
  { image: "/images/image3.png", value: "value3" },
  { image: "/images/image4.png", value: "value4" },
  { image: "/images/image4.png", value: "value4" },
  { image: "/images/image5.png", value: "value5" },
  { image: "/images/image5.png", value: "value5" },
  { image: "/images/image6.png", value: "value6" },
  { image: "/images/image6.png", value: "value6" },
  { image: "/images/image7.png", value: "value7" },
  { image: "/images/image7.png", value: "value7" },
  { image: "/images/image8.png", value: "value8" },
  { image: "/images/image8.png", value: "value8" },
  { image: "/images/image9.png", value: "value9" },
  { image: "/images/image9.png", value: "value9" },
  { image: "/images/image10.png", value: "value10" },
  { image: "/images/image10.png", value: "value10" }
];

const cards30 = [
  { image: "/images/image1.png", value: "value1" },
  { image: "/images/image1.png", value: "value1" },
  { image: "/images/image2.png", value: "value2" },
  { image: "/images/image2.png", value: "value2" },
  { image: "/images/image3.png", value: "value3" },
  { image: "/images/image3.png", value: "value3" },
  { image: "/images/image4.png", value: "value4" },
  { image: "/images/image4.png", value: "value4" },
  { image: "/images/image5.png", value: "value5" },
  { image: "/images/image5.png", value: "value5" },
  { image: "/images/image6.png", value: "value6" },
  { image: "/images/image6.png", value: "value6" },
  { image: "/images/image7.png", value: "value7" },
  { image: "/images/image7.png", value: "value7" },
  { image: "/images/image8.png", value: "value8" },
  { image: "/images/image8.png", value: "value8" },
  { image: "/images/image9.png", value: "value9" },
  { image: "/images/image9.png", value: "value9" },
  { image: "/images/image10.png", value: "value10" },
  { image: "/images/image10.png", value: "value10" },
  { image: "/images/image11.png", value: "value11" },
  { image: "/images/image11.png", value: "value11" },
  { image: "/images/image12.png", value: "value12" },
  { image: "/images/image12.png", value: "value12" },
  { image: "/images/image13.png", value: "value13" },
  { image: "/images/image13.png", value: "value13" },
  { image: "/images/image14.png", value: "value14" },
  { image: "/images/image14.png", value: "value14" },
  { image: "/images/image15.png", value: "value15" },
  { image: "/images/image15.png", value: "value15" }
];

export { cards10, cards20, cards30 };
